Repository cloudnative-pg/postgres-containers, pull requests merged in 2025-07, with the labels that each got.

#239 chore: update requirements.txt file with latest versions
  lib/repo_funcs.sh
Labels: dependencies, size:XS, lgtm

#246 fix: ensure /var/lib/postgresql/data doesn't exist is system containers
  Debian/Dockerfile-beta.template
  Debian/Dockerfile.template
Labels: bug, size:XS, lgtm

#250 chore: check for latest version of urllib3
  lib/repo_funcs.sh
Labels: size:S, lgtm

#255 docs: update image signature context
  README.md
Labels: documentation, size:XS, lgtm
