Repository cloudnative-pg/postgres-containers, pull requests merged in 2025-04, with the labels that each got.

#173 ci: stop on errors in subshells
  Debian/update.sh
Labels: size:S, lgtm

#171 ci: pin pip version
  .github/workflows/update.yml
Labels: github_actions, size:XS, lgtm

#165 Enable pinGitHubActionDigests for renovatebot
  renovate.json
Labels: size:XS, lgtm
